### PR TITLE
fix(addSidebar): Content-type adding sidebar should take into consideration default widgets [EXT-2567]

### LINKED ISSUE #661: Adding Custom sidebar widgets removes default widgets
## Expected Behavior

using .addSidebarWidget to add a new extension creates the sidebar at the end of the list of sidebar

## Actual Behavior

using .addSidebarWidget to add a new extension removes all default builtin sidebar 

## Possible Solution

We are currently using the workaround of re-creating all the built-in sidebar widgets in the migration to not blow away the defaults.

## Steps to Reproduce

1. Create a new migration script creating a new Content Type
2. use the .addSidebar migration method to add a new custom UI extension
3. run this migration on Contentful using the CLI

## Context

We came across this trying to create migrations for a new Content type and adding a translation extension to the content type. When running the migration using the CLI against Contentful, the end result has our new sidebar widget added to the content type, but all the default widgets were now removed.

Example migration:
```
module.exports = (migration) => {
    const fooContentType = migration
      .createContentType("fooContentType")
      .name("Foo Content Type")

    resourceType
      .createField("name")
      .name("Name")
      .type("Symbol")
      .localized(true)
      .required(false)
      .validations([])
      .disabled(false)
      .omitted(false);

    resourceType.displayField("name");
    // Here is our custom widget
    resourceType.addSidebarWidget("extension", "custom-extension-id")
};
```

We are currently working around this by re-adding all the default extensions:
```
    //...
    .addSidebarWidget("extension", "custom-extension-id")
    .addSidebarWidget('sidebar-builtin', 'publication-widget')
    .addSidebarWidget('sidebar-builtin', 'releases-widget')
    .addSidebarWidget('sidebar-builtin', 'content-workflows-tasks-widget')
    .addSidebarWidget('sidebar-builtin', 'content-preview-widget')
    .addSidebarWidget('sidebar-builtin', 'incoming-links-widget')
    .addSidebarWidget('sidebar-builtin', 'translation-widget')
    .addSidebarWidget('sidebar-builtin', 'versions-widget')
    .addSidebarWidget('sidebar-builtin', 'users-widget');
```

## Environment

-   **Node Version**:  12.18.3
-   **Package Manager Version**: 6.14.6
-   **Package Version**: 1.5.33

### PR DESCRIPTION
**Pull request by kdamball**
## Summary
Fixes #661

## Description
Sidebar widgets default setting is undefined which renders all default elements. Need to push the default ones plus the additional one when doing `addSidebar` on empty state.

### CODE REVIEW

**Review by shikaan — APPROVED** [review]

**Review by andipaetzold — APPROVED** [review]

File: src/lib/entities/content-type.ts [hunk 1]
```diff
@@ -179,12 +180,20 @@ class EditorInterfaces {
...
-    this._sidebar = Array.isArray(this._sidebar) ? this._sidebar : []
+  addSidebarWidget (
+    widgetId: string,
+    widgetNamespace: APISidebarWidgetNamespace,
+    settings: APISidebarWidgetSettings,
+    insertBeforeWidgetId: string,
+    disabled: boolean
+  ) {
+
+    this._sidebar = Array.isArray(this._sidebar) ? this._sidebar : [].concat(DEFAULT_SIDEBAR_LIST)
```
Comment (loweisz) [inline src/lib/entities/content-type.ts:191]: Why is that `[].concat` needed ? Isn't `DEFAULT_SIDEBAR_LIST ` already an array? 🤔

**Review by loweisz — APPROVED** [review]
LGTM 🎉  , just a small question

File: src/lib/entities/content-type.ts (hunk 1 above)
Comment (kdamball) [reply src/lib/entities/content-type.ts:191]: Just in case to avoid mutation 😬
